AWSTemplateFormatVersion: '2010-09-09'
Description: 'Portfolio Website Infrastructure'

# EDIT THIS SECTION: Change the default domain name to your preferred name
Parameters:
  DomainName:
    Type: String
    Description: Domain name for the website (will be used as bucket name prefix)
    Default: yourname-portfolio  # CHANGE THIS: Replace 'yourname' with your actual name

Resources:
  # S3 Bucket for static website hosting
  # NO EDIT NEEDED: This creates a unique bucket name using your parameter
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}-${AWS::AccountId}'  # Creates unique name
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Bucket Policy for public read access
  # NO EDIT NEEDED: This allows public access to your website files
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: WebsiteBucket
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
             Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket}/*'

  # CloudFront Distribution for global content delivery
  # NO EDIT NEEDED: This creates a CDN for your website
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: WebsiteBucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

# OUTPUTS: Copy these values after stack creation for GitHub Actions
Outputs:
  WebsiteURL:
    Description: CloudFront URL - Visit this to see your website
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
  
  S3BucketName:
    Description: S3 Bucket Name - Use this in GitHub Actions secrets
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'
  
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID - Use this in GitHub Actions secrets
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontId'